spring:
  config:
    import:
      - organisation.yaml  # or optional:classpath:organisation.yml

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"  # This exposes all endpoints
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/