spring:
  config:
    import:
      - organisation.yaml  # or optional:classpath:organisation.yml
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"  # This exposes all endpoints
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    circuitbreakers:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        ignoreExceptions:
          - java.lang.NullPointerException
        retryExceptions:
          - java.util.concurrent.TimeoutException

  ratelimiter:
    configs:
      default:
        timeoutDuration: 1000
        limitRefreshPeriod: 5000
        limitForPeriod: 1